language: minimal

branches:
  only:
  - master

jobs:
  include:
  - os: linux
    dist: bionic
    name: Lint
    before_install:
      - |
         sudo systemctl stop apt-daily.service &&
         sudo systemctl kill --kill-who=all apt-daily.service &&
         while ! (systemctl list-units --all apt-daily.service | fgrep -q dead) ; do
           sleep 1
         done
      - sudo apt update
    script:
      - bash scripts/lint.sh
  - os: linux
    dist: bionic
    name: Ubuntu 18.04 - Bionic
    before_install:
      - |
         sudo systemctl stop apt-daily.service &&
         sudo systemctl kill --kill-who=all apt-daily.service &&
         while ! (systemctl list-units --all apt-daily.service | fgrep -q dead) ; do
           sleep 1
         done
      - sudo apt update
    install:
      - bash scripts/build.sh
    script:
      - bash scripts/test.sh
    env:
      - SHREAD_TEST__UNIX_DISTRO=ubuntu

  - os: linux
    dist: focal
    name: Ubuntu 20.04 - Focal
    before_install:
      - |
         sudo systemctl stop apt-daily.service &&
         sudo systemctl kill --kill-who=all apt-daily.service &&
         while ! (systemctl list-units --all apt-daily.service | fgrep -q dead) ; do
           sleep 1
         done
      - sudo apt update
    install:
      - bash scripts/build.sh
    script:
      - bash scripts/test.sh
    env:
      - SHREAD_TEST__UNIX_DISTRO=ubuntu

  - os: linux
    dist: focal
    name: Debian 9 - Stretch
    services:
      - docker
    before_install:
      - docker pull debian:stretch
      - docker run -itd --name test debian:stretch
      - docker cp . test:/shread
    install:
      - docker exec test bash -c "apt-get update && apt-get install -y make sudo apt-utils"
      - docker exec test bash -c "useradd -m docker && echo "docker:docker" | chpasswd && adduser docker sudo"
      - docker exec -w /shread test bash -c "bash scripts/build.sh"
    script:
      - docker exec -w /shread -e SHREAD_TEST__UNIX_DISTRO=debian test bash -c "bash scripts/test.sh"

  - os: linux
    dist: focal
    name: Debian 10 - Buster
    services:
      - docker
    before_install:
      - docker pull debian:buster
      - docker run -itd --name test debian:buster
      - docker cp . test:/shread
    install:
      - docker exec test bash -c "apt-get update && apt-get install -y make sudo"
      - docker exec test bash -c "useradd -m docker && echo "docker:docker" | chpasswd && adduser docker sudo"
      - docker exec -w /shread test bash -c "bash scripts/build.sh"
    script:
      - docker exec -w /shread -e SHREAD_TEST__UNIX_DISTRO=debian test bash -c "bash scripts/test.sh"

notifications:
  email: false
