os: linux
language: shell

branches:
  only:
  - master

jobs:
  include:
  - dist: focal
    name: Lint
    before_install:
      - |
         sudo systemctl stop apt-daily.service &&
         sudo systemctl kill --kill-who=all apt-daily.service &&
         while ! (systemctl list-units --all apt-daily.service | fgrep -q dead); do
           sleep 1
         done
      - sudo apt-get update
    script:
      - bash scripts/lint.sh

  - dist: bionic
    name: Ubuntu 18.04 - Bionic
    before_install:
      - |
         sudo systemctl stop apt-daily.service &&
         sudo systemctl kill --kill-who=all apt-daily.service &&
         while ! (systemctl list-units --all apt-daily.service | fgrep -q dead); do
           sleep 1
         done
      - sudo apt-get update
    install:
      - bash scripts/build.sh
    script:
      - bash scripts/test.sh
    env:
      - SHREAD_TEST__UNIX_DISTRO=ubuntu
      - SHREAD_TEST__UNIX_DISTRO_VERSION_NAME=bionic
      - SHREAD_TEST__UNIX_DISTRO_VERSION_NUMBER=18.04

  - dist: focal
    name: Ubuntu 20.04 - Focal
    before_install:
      - |
         sudo systemctl stop apt-daily.service &&
         sudo systemctl kill --kill-who=all apt-daily.service &&
         while ! (systemctl list-units --all apt-daily.service | fgrep -q dead); do
           sleep 1
         done
      - sudo apt-get update
    install:
      - bash scripts/build.sh
    script:
      - bash scripts/test.sh
    env:
      - SHREAD_TEST__UNIX_DISTRO=ubuntu
      - SHREAD_TEST__UNIX_DISTRO_VERSION_NAME=focal
      - SHREAD_TEST__UNIX_DISTRO_VERSION_NUMBER=20.04

  - dist: focal
    name: Debian 9.12 - Stretch
    services:
      - docker
    before_install:
      - docker pull debian:stretch
      - docker run -itd --name test debian:stretch
      - docker cp . test:/shread
    install:
      - docker exec test bash -c "apt-get update && apt-get install -y make sudo apt-utils aptitude curl"
      - docker exec test bash -c "useradd -m docker && echo "docker:docker" | chpasswd && adduser docker sudo"
      - docker exec -w /shread test bash -c "bash scripts/build.sh"
    script:
      - docker exec test bash -c "echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections"
      - docker exec -w /shread -e SHREAD_TEST__UNIX_DISTRO=debian -e SHREAD_TEST__UNIX_DISTRO_VERSION_NAME=stretch -e SHREAD_TEST__UNIX_DISTRO_VERSION_NUMBER=9.13 -e GITHUB_USERNAME=$GITHUB_USERNAME -e GITHUB_TOKEN=$GITHUB_TOKEN test bash -c "bash scripts/test.sh"

  - os: linux
    dist: focal
    name: Debian 10 - Buster
    services:
      - docker
    before_install:
      - docker pull debian:buster
      - docker run -itd --name test debian:buster
      - docker cp . test:/shread
    install:
      - docker exec test bash -c "apt-get update && apt-get install -y make sudo apt-utils aptitude curl"
      - docker exec test bash -c "useradd -m docker && echo "docker:docker" | chpasswd && adduser docker sudo"
      - docker exec -w /shread test bash -c "bash scripts/build.sh"
    script:
      - docker exec -w /shread -e SHREAD_TEST__UNIX_DISTRO=debian -e SHREAD_TEST__UNIX_DISTRO_VERSION_NAME=buster -e SHREAD_TEST__UNIX_DISTRO_VERSION_NUMBER=10 -e GITHUB_USERNAME=$GITHUB_USERNAME -e GITHUB_TOKEN=$GITHUB_TOKEN test bash -c "bash scripts/test.sh"

notifications:
  email: false
