language: bash

install:
  - bash scripts/build.sh

script:
  - printf "Testing on $TRAVIS_OS_NAME $TRAVIS_DIST.\n"
  - bash scripts/test.sh

branches:
  only:
  - master

jobs:
  include:
  - os: linux
    dist: bionic
    name: bionic
    language: minimal
    before_install:
      - |
         sudo systemctl stop apt-daily.service &&
         sudo systemctl kill --kill-who=all apt-daily.service &&
         while ! (systemctl list-units --all apt-daily.service | fgrep -q dead) ; do
           sleep 1
         done
      - sudo apt update
  - os: linux
    dist: focal
    name: focal
    language: minimal
    before_install:
      - |
         sudo systemctl stop apt-daily.service &&
         sudo systemctl kill --kill-who=all apt-daily.service &&
         while ! (systemctl list-units --all apt-daily.service | fgrep -q dead) ; do
           sleep 1
         done
      - sudo apt update
notifications:
  email: false
