name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
  workflow_dispatch:

env:
  GITHUB_USERNAME: mondeja
  GITHUB_TOKEN: '{{ secrets.SHREAD_TOK }}'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
         sudo systemctl stop apt-daily.service && sudo systemctl kill --kill-who=all apt-daily.service && while ! (systemctl list-units --all apt-daily.service | fgrep -q dead); do sleep 1; done
         sudo apt-get update && sudo apt-get install python3 gettext
      - name: Lint
        run: bash scripts/lint.sh

  ubuntu-bionic:
    name: Ubuntu 18.04 - Bionic
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
         sudo systemctl stop apt-daily.service && sudo systemctl kill --kill-who=all apt-daily.service && while ! (systemctl list-units --all apt-daily.service | fgrep -q dead); do sleep 1; done
         sudo apt-get update
         sudo apt-get install python3 python3-pip gettext
      - name: Build
        run: bash scripts/build.sh
      - name: Test
        run: bash scripts/test.sh
        env:
          SHREAD_TEST__UNIX_DISTRO: ubuntu
          SHREAD_TEST__UNIX_DISTRO_VERSION_NAME: bionic
          SHREAD_TEST__UNIX_DISTRO_VERSION_NUMBER: '18.04'
          SHREAD_TEST__ATOM_MUST_NOT_BE_INSTALLED: 'true'

  ubuntu-focal:
    name: Ubuntu 20.04 - Focal
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
         sudo systemctl stop apt-daily.service && sudo systemctl kill --kill-who=all apt-daily.service && while ! (systemctl list-units --all apt-daily.service | fgrep -q dead); do sleep 1; done
         sudo apt-get update
         sudo apt-get install python3 python3-pip gettext
      - name: Build
        run: bash scripts/build.sh
      - name: Test
        run: bash scripts/test.sh
        env:
          SHREAD_TEST__UNIX_DISTRO: ubuntu
          SHREAD_TEST__UNIX_DISTRO_VERSION_NAME: focal
          SHREAD_TEST__UNIX_DISTRO_VERSION_NUMBER: '20.04'
          SHREAD_TEST__ATOM_MUST_NOT_BE_INSTALLED: 'true'

  debian-stretch:
    name: Debian 9.13 - Stretch
    runs-on: ubuntu-latest
    container:
      image: debian:stretch
      options: --name test
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
          printf "deb http://deb.debian.org/debian stretch main contrib non-free\ndeb-src http://deb.debian.org/debian stretch main contrib non-free\n\ndeb http://deb.debian.org/debian-security/ stretch/updates main contrib non-free\ndeb-src http://deb.debian.org/debian-security/ stretch/updates main contrib non-free\n\ndeb http://deb.debian.org/debian stretch-updates main contrib non-free\ndeb-src http://deb.debian.org/debian stretch-updates main contrib non-free\n" > /etc/apt/sources.list
          apt-get update
          apt-get install -y make sudo apt-utils dialog aptitude curl wget ca-certificates apt-transport-https gnupg2 python3 python3-pip gettext
          useradd -m docker && echo 'docker:docker' | chpasswd && adduser docker sudo
      - name: Build
        run: bash scripts/build.sh
      - name: Test
        run: bash scripts/test.sh
        env:
          SHREAD_TEST__UNIX_DISTRO: debian
          SHREAD_TEST__UNIX_DISTRO_VERSION_NAME: stretch
          SHREAD_TEST__UNIX_DISTRO_VERSION_NUMBER: '9.13'
          SHREAD_TEST__ATOM_MUST_NOT_BE_INSTALLED: 'true'

  debian-buster:
    name: Debian 10 - Buster
    runs-on: ubuntu-latest
    container:
      image: debian:buster
      options: --name test
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
          apt-get update
          apt-get install -y make sudo apt-utils dialog aptitude curl wget ca-certificates apt-transport-https gnupg2 python3 python3-pip gettext
          useradd -m docker && echo 'docker:docker' | chpasswd && adduser docker sudo
      - name: Build
        run: bash scripts/build.sh
      - name: Test
        run: bash scripts/test.sh
        env:
          SHREAD_TEST__UNIX_DISTRO: debian
          SHREAD_TEST__UNIX_DISTRO_VERSION_NAME: buster
          SHREAD_TEST__UNIX_DISTRO_VERSION_NUMBER: '10'
          SHREAD_TEST__ATOM_MUST_NOT_BE_INSTALLED: 'true'
